### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by evilz** [Wikiki/bulma-pageloader#1]
Hi,

What about adding a modifier to make loader more transparent ?

**Comment by Wikiki** [comment]
Hi @evilz ,

which part would you like to manage ? Background opacity ?

Regards,

**Comment by evilz** [comment]
I've got un mind the background. 
A bit like modal background Can ne.

**Comment by Wikiki** [comment]
Sure.

I'll do it.

**Comment by Wikiki** [comment]
Done.
