### ISSUE TITLE
There is no documentation

### ISSUE THREAD

**Issue by ghost** [Wikiki/bulma-pageloader#11]
https://github.com/Wikiki/bulma-pageloader
Links to 
https://wikiki.github.io/elements/pageloader/
Which links back to GitHub.

Neither of them have documentation on how to use the page loader. 
:(

I've figured out
 `npm i bulma-pageloader`
And
`import 'bulma-pageloader';`
To get
`<div class="pageloader"><span class="title">Loading...</span></div>`
But I don't see it because I don't know what else I am supposed to do.

**Comment by Wikiki** [comment]
To get the pageloader displayed just add ```is-active``` class to the pageloader element.

**Comment by Roeefl** [comment]
This has very poor documentation and is quite frustrating to use, would like to add some this week with your blessing @Wikiki

**Comment by Wikiki** [comment]
hi @Roeefl,

Sorry I'm quite busy and don't have much time to work on it. Feel free to add more detailed documentation. Thanks a lot

**Comment by reedjones** [comment]
yeah these really need to be documented spent a while looking around to find this

**Comment by Roeefl** [comment]
@Wikiki Never got around to it, but you may wanna at least add the necessity of `is-active` if it is indeed needed to see the pageloader and is not at all mentioned in documentation

**Comment by codebuilderspk** [comment]
@Roeefl  yes, you are tight. it took me almost an hour to reach here. ;(

**Comment by Wikiki** [comment]
Documentation has been updated to display this information.
