### ISSUE TITLE
Problem with the pageloader extension with laravel-mix

### ISSUE THREAD

**Issue by aocneanu** [Wikiki/bulma-pageloader#3]
Hi,

When I do `npm run dev` with the pageloader extension enabled I get the following error:

```
resolve-url-loader cannot operate: CSS error
  /Users/user/code/project/resources/assets/sass/app.scss:11014:3: @keyframes missing '}'
  at error (/Users/user/code/project/node_modules/css/lib/parse/index.js:62:15)
```

I also opened laravel-frontend-presets/bulma#5

**Comment by Wikiki** [comment]
Hi @aocneanu,

This extension uses sass and not scss, there is no {} used in its code. I think you should see with laravel-frontend-presets project.

Regards

**Comment by Laraveldeep** [comment]
@Wikiki I have tested also. Seems like keyframes mixin is causing the problem on laravel-mix (or webpack).

```
@keyframes missing '}'
```
any clue?

**Comment by aocneanu** [comment]
I encountered this without the laravel-bulma preset too.

**Comment by Wikiki** [comment]
It seems to be linked to webpack.
Sorry I have no clue about it.

**Comment by aocneanu** [comment]
It's the same problem with the switch extension.

**Comment by Wikiki** [comment]
Hi @aocneanu,

As said before, it's related to webpack and there is nondeclaration of keyframes within switch extension.

For the pageloader sass, if it really the keyframes mixin declared into the extension I'll need some help because it's passing all my sass compilation tests

**Comment by aocneanu** [comment]
I just wanted to let you know that switch is affected by this too.

Thanks.

**Comment by Wikiki** [comment]
Thanks @aocneanu but based on the fact that switch does not use keyframes, are you sure it only appears when you add switch extension to a clean Bulma project ?

**Comment by Wikiki** [comment]
Thanks to @Grummfy for the fix

**Comment by Grummfy** [comment]
is it possible to release a new version?

**Comment by Wikiki** [comment]
I'll do it today.
