### ISSUE TITLE
Pageloader won't build

### ISSUE THREAD

**Issue by events-jonas-chrisw** [Wikiki/bulma-pageloader#8]
Tried pulling the files via npm..

Won;t build in webpack because there are these references at the top of the sass file:

@import "initial-variables.sass"
@import "functions.sass"
@import "derived-variables.sass"
@import "animations.sass"
@import "mixins.sass"
@import "controls.sass"

They don't exist in the filepath. Surely these are loaded via bulma anyway?!?!

**Comment by Wikiki** [comment]
Hi,

I forgot to update npm package.
It's done now.
