### ISSUE TITLE
[Question] Can this be used without npm?

### ISSUE THREAD

**Issue by jahirfiquitiva** [Wikiki/bulma-pageloader#9]

**Comment by Wikiki** [comment]
Hi,

I'm not sure to really understand your question but the documentation page explains how to use it from the github repository.

Regards

**Comment by jahirfiquitiva** [comment]
@Wikiki 

I meant like importing the css/js in html from cdnjs or something similar to this:
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
```

**Comment by Wikiki** [comment]
There is no cdjns provided. You can integrate dist folder directly into your sources and then import .min.js and .min.css files to your project.

**Comment by jahirfiquitiva** [comment]
@Wikiki oh oh, thanks :)
